BEGIN TRAN

BEGIN TRY
	UPDATE PRESTAMO
	SET F_DEVOL = '2018-03-05'
	WHERE NRO_COPIA = 1 AND NRO_LECTOR = 1 AND NRO_COPIA = 1
END TRY

BEGIN CATCH
    PRINT 'ERROR'
    --ROLLBACK TRAN
END CATCH

ROLLBACK