---- TP2 BD2 Comision C -----
---- Mateucci - Romera ----


--- En caso de INSERT en tabla PRESTAMO ---
-- Al insertar en la tabla de PRESTAMO setea la copia del libro en 'P' si esta disponible

-- TRANSACCION

BEGIN TRAN

BEGIN TRY
	INSERT INTO PRESTAMO (NRO_LECTOR, NRO_LIBRO, NRO_COPIA, F_PREST, F_DEVOL)
	VALUES (123456, 10545377, 2, '2018-06-10 10:10:10:100', NULL)
	COMMIT TRAN
END TRY
	
BEGIN CATCH
	PRINT @@ERROR
	ROLLBACK TRAN
END CATCH


-- TRIGGER

ALTER TRIGGER [dbo].[TINS_PREST] ON [dbo].[PRESTAMO] FOR INSERT AS

DECLARE @NRO_COPIA int
DECLARE @NRO_LIBRO int 

SELECT @NRO_LIBRO = NRO_LIBRO FROM INSERTED
SELECT @NRO_COPIA = NRO_COPIA FROM INSERTED

BEGIN
	PRINT 'TRIGGER INSERT'
	EXEC sp_ins_prest @NRO_COPIA, @NRO_LIBRO
END


-- STORED PROCEDURE

ALTER PROCEDURE [dbo].[sp_ins_prest]
@NRO_COPIA int,
@NRO_LIBRO int
AS

DECLARE @ESTADO char
SET @ESTADO = (SELECT ESTADO FROM COPIAS WHERE NRO_LIBRO = @NRO_LIBRO AND NRO_COPIA = @NRO_COPIA)

PRINT 'STORED PROCEDURE INSERT'

BEGIN
	IF (@ESTADO = 'D')
	BEGIN
		UPDATE COPIAS SET ESTADO = 'P' WHERE NRO_LIBRO = @NRO_LIBRO AND NRO_COPIA = @NRO_COPIA
	END
	IF (@ESTADO = 'N')
	BEGIN
		RAISERROR('COPIA EN ESTADO N', 16, 1)
	END
	IF (@ESTADO = 'P')
	BEGIN
		RAISERROR('COPIA EN ESTADO P', 16, 1)
	END
END


--- En caso de UPDATE en tabla PRESTAMO ---
-- Devolucion de un prestamo. Setea la fecha de devolucion y el estado 'D' a la copia devuelta.

-- TRANSACCION

BEGIN TRAN

BEGIN TRY
	UPDATE PRESTAMO 
		SET F_DEVOL = GETDATE() 
		WHERE NRO_COPIA = 2 AND NRO_LIBRO = 10545377 AND NRO_LECTOR = 123456
	COMMIT TRAN
END TRY

BEGIN CATCH
    PRINT @@ERROR
    ROLLBACK TRAN
END CATCH


-- TRIGGER

ALTER TRIGGER [dbo].[T_UPT_PREST] ON [dbo].[PRESTAMO] FOR UPDATE AS

DECLARE @F_DEVOL datetime
DECLARE @NRO_LIBRO int
DECLARE @NRO_COPIA int

SELECT @F_DEVOL = PRESTAMO.F_DEVOL FROM INSERTED PRESTAMO
SELECT @NRO_LIBRO = PRESTAMO.NRO_LIBRO FROM INSERTED PRESTAMO
SELECT @NRO_COPIA = PRESTAMO.NRO_COPIA FROM INSERTED PRESTAMO

BEGIN
	PRINT 'TRIGGER UPDATE'
	EXEC sp_upd_prest @NRO_COPIA, @NRO_LIBRO, @F_DEVOL
END


-- STORED PROCEDURE

ALTER PROCEDURE [dbo].[sp_upd_prest]
@NRO_COPIA int,
@NRO_LIBRO int,
@F_DEVOL datetime
AS

PRINT 'STORED PROCEDURE UPDATE'

BEGIN
	UPDATE COPIAS SET ESTADO = 'D' WHERE NRO_LIBRO = @NRO_LIBRO AND NRO_COPIA = @NRO_COPIA
END


--- Creacion de tabla con valores DEFAULT/CHECK
-- Crea la tabla de COPIAS seteando como DEFAULT el ESTADO 'D' y los estados validos mencionados en el enunciado

CREATE TABLE COPIAS (
	NRO_LIBRO int NOT NULL,
	NRO_COPIA smallint NOT NULL ,
	ESTADO char(1) NOT NULL DEFAULT ('D')
	 
	CONSTRAINT estados_validos
	CHECK(ESTADO ='P' OR ESTADO ='D' OR ESTADO ='N'))


-- Crea la tabla de LIBRO seteando como DEFAULT el ESTADO 'D' y los estados validos mencionados en el enunciado

CREATE TABLE LIBRO (
	NRO_LIBRO int NOT NULL PRIMARY KEY, 
    TITULO char(40),
    AUTOR char(30),
    TIPO char(2) FOREIGN KEY REFERENCES TIPOLIBRO (TIPO),
	PRECIO_ORI smallmoney,
    PRECIO_ACT smallmoney, 
    EDICION smallint,
	ESTADO char(1) NOT NULL DEFAULT ('D')
	       	    
	CONSTRAINT estados_validos
	CHECK(ESTADO ='D' OR ESTADO ='N'))
